version: '3'
services:
  # docker-test-db 폴더에 있는 Dockerfile을 빌드
  db:
    build:
      context: ./docker-test-db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    # ./docker-test-db/store에 /var/lib/mysql의 데이터 저장(볼륨)
    volumes:
     - ./docker-test-db/store:/var/lib/mysql
    networks:
     - network
  server:
    build:
      context: ./docker-test-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    # db가 모두 구축되고 나서 server가 실행
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/metadb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    networks:
     - network

networks:
 network: